### ISSUE TITLE
iPhoto添加相册后提示“ApiError: Internal Server Error”

### ISSUE THREAD

**Issue by dockylf** [Carseason/iphotos#2]
背景：
1、此前从未设置过routerdog里的“cloud”本地数据存储路径，一直是用默认的/tmp。
2、此次更新出现iPhoto后，看到需要先设置存储路径才能使用后，就更改了路径为外接硬盘，/mnt/sda1/configs。更改完正常，初始化状态显示“已初始化”
问题：
3、打开iPhoto，添加相册，相册地址也在外接硬盘里，/mnt/sda1/DK的相册。
4、添加相册后，点击全部相册，即出现“ApiError: Internal Server Error”提示，且此时cloud里的初始化状态变成了”未初始化“。
尝试措施：
5、存储路径重新改为/tmp，并删除 /mnt/sda1/configs/routerdog文件夹，重启。
6、修改相册文件夹名为纯英文。
执行5、6措施后，继续按2、3、4步操作，问题复现。

**Comment by Carseason** [comment]
你进群里让我远程一下？133827925 群

**Comment by Carseason** [comment]
看看是不是只读分区

**Comment by dockylf** [comment]
> 看看是不是只读分区

Solved.
我之前勾选了EXIF信息和人物信息。重新添加相册时取消这两个勾选，就不报错了。

**Comment by Carseason** [comment]
最好提供一下一些错误的照片或者错误信息。。。

**Comment by Carseason** [comment]
正常勾选这两个也是没问题的，最好帮我定位一下哈
