### ISSUE TITLE
已经添加的相册怎么删除？添加的个别照片怎么删除？

### ISSUE THREAD

**Issue by mzt-1988** [Carseason/iphotos#4]
已经添加的相册和照片怎么删除？

**Comment by Carseason** [comment]
相册右上角的小点点

**Comment by mzt-1988** [comment]
> 相册右上角的小点点



> 相册右上角的小点点

我的相册封面是白色的，小点点应该也是白色的，所以我看不到。提个建议，把功能放在相册框外边，或者对比度增大
